import { Product } from './types';

export const mockProducts: Product[] = [
  { 
    id: 1, 
    name: 'Classic Trench Coat', 
    category: 'Coats', 
    price: 220.00, 
    imageUrl: 'https://picsum.photos/400/500?random=1',
    images: [
      'https://picsum.photos/800/1000?random=1',
      'https://picsum.photos/800/1000?random=11',
      'https://picsum.photos/800/1000?random=12',
      'https://picsum.photos/800/1000?random=13',
    ],
    description: "A timeless outerwear piece, this trench coat is crafted from water-resistant cotton gabardine. It features a double-breasted closure, a belted waist, and epaulets for a classic military-inspired look. Perfect for transitional weather.",
    reviews: [
      { id: 1, author: 'Jane D.', rating: 5, comment: 'Absolutely stunning! The quality is amazing and it fits perfectly.', date: '2023-10-15' },
      { id: 2, author: 'John S.', rating: 4, comment: 'Great coat, very stylish. A bit lighter than I expected but still great.', date: '2023-10-12' },
    ],
    isNew: true 
  },
  { 
    id: 2, 
    name: 'Slim Fit Chinos', 
    category: 'Pants', 
    price: 85.00, 
    originalPrice: 110.00, 
    imageUrl: 'https://picsum.photos/400/500?random=2',
    images: [
      'https://picsum.photos/800/1000?random=2',
      'https://picsum.photos/800/1000?random=21',
      'https://picsum.photos/800/1000?random=22',
    ],
    description: "Our signature slim-fit chinos are made from comfortable stretch cotton twill and washed for a soft, broken-in feel. A versatile staple for any modern wardrobe, they can be dressed up or down with ease.",
    reviews: [
      { id: 3, author: 'Mike R.', rating: 5, comment: 'Best chinos I have ever owned. The fit is perfect.', date: '2023-09-28' },
    ],
  },
  { 
    id: 3, 
    name: 'Leather Loafers', 
    category: 'Shoes', 
    price: 150.00, 
    imageUrl: 'https://picsum.photos/400/500?random=3',
    images: [
      'https://picsum.photos/800/1000?random=3',
      'https://picsum.photos/800/1000?random=31',
      'https://picsum.photos/800/1000?random=32',
      'https://picsum.photos/800/1000?random=33',
    ],
    description: "Handcrafted from supple calfskin leather, these loafers feature a classic penny-keeper detail and a durable leather sole. They offer timeless style and all-day comfort, making them a smart investment.",
    reviews: [
      { id: 4, author: 'Emily W.', rating: 5, comment: 'So comfortable and elegant. I get compliments every time I wear them.', date: '2023-10-20' },
      { id: 5, author: 'David L.', rating: 4, comment: 'Beautiful shoes, just need a little breaking in.', date: '2023-10-18' },
    ],
  },
  { 
    id: 4, 
    name: 'Cashmere V-Neck Sweater', 
    category: 'Sweaters', 
    price: 180.00,
    originalPrice: 220.00,
    imageUrl: 'https://picsum.photos/400/500?random=4',
    images: [
      'https://picsum.photos/800/1000?random=4',
      'https://picsum.photos/800/1000?random=41',
    ],
    description: "Experience unparalleled softness with our V-neck sweater, knit from the finest Mongolian cashmere. It has a classic fit that's easy to layer and is finished with ribbed trim at the collar, cuffs, and hem.",
    reviews: [],
  },
  { 
    id: 5, 
    name: 'Denim Jacket', 
    category: 'Jackets', 
    price: 120.00, 
    imageUrl: 'https://picsum.photos/400/500?random=5',
    images: [
      'https://picsum.photos/800/1000?random=5',
      'https://picsum.photos/800/1000?random=51',
      'https://picsum.photos/800/1000?random=52',
    ],
    description: "An iconic essential, our denim jacket is made from durable cotton denim with a hint of stretch for comfort. It's designed with a point collar, buttoned front, and classic welt pockets. A true wardrobe workhorse.",
    reviews: [
      { id: 6, author: 'Sarah K.', rating: 5, comment: 'The perfect denim jacket. Great fit and color.', date: '2023-10-05' },
    ],
    isNew: true 
  },
  { 
    id: 6, 
    name: 'Silk Scarf', 
    category: 'Accessories', 
    price: 60.00, 
    imageUrl: 'https://picsum.photos/400/500?random=6',
    images: [
      'https://picsum.photos/800/1000?random=6',
      'https://picsum.photos/800/1000?random=61',
    ],
    description: "Add a touch of luxury to any outfit with this beautiful scarf, crafted from pure silk with an elegant print. It features finely rolled edges and has a lightweight feel, making it perfect for year-round wear.",
    reviews: [
       { id: 7, author: 'Olivia C.', rating: 5, comment: 'The pattern is even more beautiful in person. The silk is so soft.', date: '2023-10-22' },
    ],
  },
  { 
    id: 7, 
    name: 'Striped Oxford Shirt', 
    category: 'Shirts', 
    price: 95.00, 
    originalPrice: 125.00, 
    imageUrl: 'https://picsum.photos/400/500?random=7',
    images: [
      'https://picsum.photos/800/1000?random=7',
      'https://picsum.photos/800/1000?random=71',
      'https://picsum.photos/800/1000?random=72',
    ],
    description: "A preppy classic, our Oxford shirt is cut from soft, breathable cotton and features a timeless stripe pattern. It's detailed with a button-down collar, a chest pocket, and our signature embroidered logo.",
    reviews: [
      { id: 8, author: 'Ben A.', rating: 5, comment: 'Classic shirt, fits well and looks sharp.', date: '2023-09-15' },
    ],
  },
  { 
    id: 8, 
    name: 'Wool Beanie', 
    category: 'Accessories', 
    price: 45.00, 
    imageUrl: 'https://picsum.photos/400/500?random=8',
    images: [
      'https://picsum.photos/800/1000?random=8',
      'https://picsum.photos/800/1000?random=81',
    ],
    description: "Stay warm in style with this classic beanie, knitted from soft and insulating merino wool. It features a ribbed construction and a turn-up cuff for a snug, comfortable fit.",
    reviews: [],
  },
  { 
    id: 9, 
    name: 'Wool Peacoat', 
    category: 'Coats', 
    price: 250.00, 
    imageUrl: 'https://picsum.photos/400/500?random=90',
    images: [
      'https://picsum.photos/800/1000?random=90',
      'https://picsum.photos/800/1000?random=91',
    ],
    description: "A timeless winter staple, this peacoat is tailored from a warm wool blend. It features a classic double-breasted front, notch lapels, and anchor-embossed buttons. Fully lined for extra warmth and comfort.",
    reviews: [
      { id: 9, author: 'Chris G.', rating: 5, comment: 'Fantastic quality and very warm. Perfect for winter.', date: '2023-11-01' },
    ],
  },
  { 
    id: 10, 
    name: 'Straight Fit Jeans', 
    category: 'Pants', 
    price: 110.00,
    imageUrl: 'https://picsum.photos/400/500?random=100',
    images: [
      'https://picsum.photos/800/1000?random=100',
      'https://picsum.photos/800/1000?random=101',
      'https://picsum.photos/800/1000?random=102',
    ],
    description: "Crafted from premium selvedge denim, these jeans have a classic straight-leg fit. They're washed for a lived-in look and feature traditional five-pocket styling and a zip fly. A versatile foundation for any casual look.",
    reviews: [
      { id: 10, author: 'Alex P.', rating: 5, comment: 'Great pair of jeans. The denim feels high quality.', date: '2023-10-25' },
    ],
    isNew: true
  },
  { 
    id: 11, 
    name: 'Suede Ankle Boots', 
    category: 'Shoes', 
    price: 175.00, 
    originalPrice: 200.00,
    imageUrl: 'https://picsum.photos/400/500?random=110',
    images: [
      'https://picsum.photos/800/1000?random=110',
      'https://picsum.photos/800/1000?random=111',
      'https://picsum.photos/800/1000?random=112',
    ],
    description: "These ankle boots are expertly crafted in Italy from rich suede. They have a sleek almond-toe shape and are set on a comfortable stacked heel. A side zip closure makes them easy to slip on and off.",
    reviews: [],
  },
  { 
    id: 12, 
    name: 'Crewneck Cotton Sweater', 
    category: 'Sweaters', 
    price: 90.00,
    imageUrl: 'https://picsum.photos/400/500?random=120',
    images: [
      'https://picsum.photos/800/1000?random=120',
      'https://picsum.photos/800/1000?random=121',
    ],
    description: "An essential layering piece, this sweater is knit from soft, breathable Pima cotton. It has a classic crewneck and is finished with ribbed trim. Perfect for year-round wear.",
    reviews: [
        { id: 11, author: 'Jessica M.', rating: 4, comment: 'Nice lightweight sweater. Good for layering.', date: '2023-10-10' },
    ],
  },
  { 
    id: 13, 
    name: 'Quilted Bomber Jacket', 
    category: 'Jackets', 
    price: 160.00,
    imageUrl: 'https://picsum.photos/400/500?random=130',
    images: [
      'https://picsum.photos/800/1000?random=130',
      'https://picsum.photos/800/1000?random=131',
      'https://picsum.photos/800/1000?random=132',
    ],
    description: "This bomber jacket is made from a water-repellent shell and lightly filled for warmth. It features a diamond-quilted pattern, a zip front, and ribbed trim at the collar, cuffs, and hem. A modern take on a classic silhouette.",
    reviews: [],
    isNew: true
  },
  { 
    id: 14, 
    name: 'Linen Button-Down Shirt', 
    category: 'Shirts', 
    price: 88.00,
    imageUrl: 'https://picsum.photos/400/500?random=140',
    images: [
      'https://picsum.photos/800/1000?random=140',
      'https://picsum.photos/800/1000?random=141',
    ],
    description: "Perfect for warm weather, this shirt is woven from lightweight and breathable linen. It has a relaxed fit, a classic point collar, and a buttoned front. Roll up the sleeves for an even more laid-back look.",
    reviews: [
        { id: 12, author: 'Matt D.', rating: 5, comment: 'Great shirt for summer. Very comfortable and breathable.', date: '2023-08-20' },
    ],
  },
  { 
    id: 15, 
    name: 'Parka with Faux Fur Hood', 
    category: 'Coats', 
    price: 280.00, 
    imageUrl: 'https://picsum.photos/400/500?random=150',
    images: [
      'https://picsum.photos/800/1000?random=150',
      'https://picsum.photos/800/1000?random=151',
    ],
    description: "Brave the elements in this durable parka, featuring a cozy faux-fur-trimmed hood, fleece-lined pockets, and a water-resistant shell. An essential for cold-weather adventures.",
    reviews: [],
    isNew: true
  },
  {
    id: 16,
    name: 'Utility Cargo Pants',
    category: 'Pants',
    price: 98.00,
    imageUrl: 'https://picsum.photos/400/500?random=160',
    images: [
      'https://picsum.photos/800/1000?random=160',
      'https://picsum.photos/800/1000?random=161',
    ],
    description: 'Made from durable cotton ripstop, these cargo pants feature multiple utility pockets and a comfortable, relaxed fit. Perfect for a casual, rugged look.',
    reviews: [
      { id: 13, author: 'Tom H.', rating: 5, comment: 'Love these pants. So practical and stylish.', date: '2023-11-05' },
    ],
  },
  {
    id: 17,
    name: 'Classic Leather Sneakers',
    category: 'Shoes',
    price: 130.00,
    originalPrice: 160.00,
    imageUrl: 'https://picsum.photos/400/500?random=170',
    images: [
      'https://picsum.photos/800/1000?random=170',
      'https://picsum.photos/800/1000?random=171',
    ],
    description: 'A timeless court-inspired sneaker crafted from smooth leather. It features a clean, minimalist design with a comfortable rubber sole, making it a versatile choice for everyday wear.',
    reviews: [],
  },
  {
    id: 18,
    name: 'Merino Wool Turtleneck',
    category: 'Sweaters',
    price: 145.00,
    imageUrl: 'https://picsum.photos/400/500?random=180',
    images: [
      'https://picsum.photos/800/1000?random=180',
    ],
    description: 'A sophisticated essential, this turtleneck sweater is spun from extra-fine merino wool for a soft and lightweight feel. It has a slim fit that makes it perfect for layering.',
    reviews: [
      { id: 14, author: 'Sophia L.', rating: 5, comment: 'Incredibly soft and looks so chic. A winter wardrobe staple.', date: '2023-11-10' },
    ],
  },
  {
    id: 19,
    name: 'Leather Biker Jacket',
    category: 'Jackets',
    price: 350.00,
    originalPrice: 400.00,
    imageUrl: 'https://picsum.photos/400/500?random=190',
    images: [
      'https://picsum.photos/800/1000?random=190',
      'https://picsum.photos/800/1000?random=191',
    ],
    description: 'Crafted from supple lambskin leather, this biker jacket has an effortlessly cool appeal. It features asymmetric zip fastenings, notched lapels, and multiple zip pockets. A timeless investment piece.',
    reviews: [],
  },
  {
    id: 20,
    name: 'Reversible Leather Belt',
    category: 'Accessories',
    price: 75.00,
    imageUrl: 'https://picsum.photos/400/500?random=200',
    images: [
      'https://picsum.photos/800/1000?random=200',
    ],
    description: 'Two looks in one, this versatile belt is crafted from smooth leather that reverses from black to brown. It\'s finished with a polished silver-tone buckle.',
    reviews: [],
  },
  {
    id: 21,
    name: 'Pique Polo Shirt',
    category: 'Shirts',
    price: 75.00,
    imageUrl: 'https://picsum.photos/400/500?random=210',
    images: [
      'https://picsum.photos/800/1000?random=210',
      'https://picsum.photos/800/1000?random=211',
    ],
    description: 'Our iconic polo shirt is made from breathable cotton pique and tailored for a comfortable, classic fit. It features a ribbed collar and cuffs and our signature embroidered logo at the chest.',
    reviews: [
      { id: 15, author: 'George K.', rating: 5, comment: 'Can\'t go wrong with this classic. Great fit and quality.', date: '2023-10-01' },
    ],
  },
  { 
    id: 22, 
    name: 'Duffle Coat', 
    category: 'Coats', 
    price: 260.00, 
    imageUrl: 'https://picsum.photos/400/500?random=220',
    images: ['https://picsum.photos/800/1000?random=220'],
    description: "A classic duffle coat made from a warm wool blend, featuring traditional toggle fastenings and a large hood. The perfect companion for cold winter days.",
    reviews: [],
  },
  { 
    id: 23, 
    name: 'Lightweight Raincoat', 
    category: 'Coats', 
    price: 130.00, 
    imageUrl: 'https://picsum.photos/400/500?random=230',
    images: ['https://picsum.photos/800/1000?random=230'],
    description: "Stay dry without the bulk. This lightweight raincoat is fully waterproof with sealed seams and a breathable design, making it ideal for unpredictable weather.",
    reviews: [],
    isNew: true,
  },
  {
    id: 24,
    name: 'Pleated Trousers',
    category: 'Pants',
    price: 115.00,
    imageUrl: 'https://picsum.photos/400/500?random=240',
    images: ['https://picsum.photos/800/1000?random=240'],
    description: 'Sophisticated and modern, these trousers are tailored with sharp front pleats for a relaxed, tapered silhouette. Woven from a fine wool blend for a comfortable drape.',
    reviews: [],
  },
  {
    id: 25,
    name: 'Drawstring Linen Pants',
    category: 'Pants',
    price: 90.00,
    imageUrl: 'https://picsum.photos/400/500?random=250',
    images: ['https://picsum.photos/800/1000?random=250'],
    description: 'The epitome of relaxed style, these pants are made from breathable linen and feature a comfortable drawstring waist. Perfect for vacations or warm weekends.',
    reviews: [],
  },
  {
    id: 26,
    name: 'Driving Moccasins',
    category: 'Shoes',
    price: 160.00,
    imageUrl: 'https://picsum.photos/400/500?random=260',
    images: ['https://picsum.photos/800/1000?random=260'],
    description: 'Crafted from soft suede with a flexible pebble rubber sole, these driving moccasins provide exceptional comfort and a refined, casual look.',
    reviews: [],
  },
  {
    id: 27,
    name: 'Wingtip Brogues',
    category: 'Shoes',
    price: 210.00,
    imageUrl: 'https://picsum.photos/400/500?random=270',
    images: ['https://picsum.photos/800/1000?random=270'],
    description: 'A timeless dress shoe, these brogues are made from polished calfskin leather and feature traditional wingtip detailing and perforations. A Goodyear-welted sole ensures durability.',
    reviews: [],
  },
  {
    id: 28,
    name: 'Cable-Knit Crewneck',
    category: 'Sweaters',
    price: 130.00,
    imageUrl: 'https://picsum.photos/400/500?random=280',
    images: ['https://picsum.photos/800/1000?random=280'],
    description: 'A heritage-inspired classic, this sweater is knitted from soft cotton in a traditional cable-knit pattern. A versatile piece for smart-casual looks.',
    reviews: [],
  },
  {
    id: 29,
    name: 'Half-Zip Mock Neck Sweater',
    category: 'Sweaters',
    price: 110.00,
    imageUrl: 'https://picsum.photos/400/500?random=290',
    images: ['https://picsum.photos/800/1000?random=290'],
    description: 'This versatile sweater is made from soft Pima cotton and features a mock neck with a half-zip placket. An ideal layering piece for the office or weekend.',
    reviews: [],
    isNew: true,
  },
  {
    id: 30,
    name: 'Canvas Field Jacket',
    category: 'Jackets',
    price: 195.00,
    originalPrice: 240.00,
    imageUrl: 'https://picsum.photos/400/500?random=300',
    images: ['https://picsum.photos/800/1000?random=300'],
    description: 'Inspired by classic military outerwear, this field jacket is cut from durable cotton canvas and features multiple utility pockets, a stand collar, and a concealed hood.',
    reviews: [],
  },
  {
    id: 31,
    name: 'Cashmere Baseball Cap',
    category: 'Accessories',
    price: 85.00,
    imageUrl: 'https://picsum.photos/400/500?random=310',
    images: ['https://picsum.photos/800/1000?random=310'],
    description: 'A luxurious take on a sporty classic, this baseball cap is crafted from plush cashmere and features an adjustable leather strap for a perfect fit.',
    reviews: [],
  },
  {
    id: 32,
    name: 'Patterned Pocket Square',
    category: 'Accessories',
    price: 40.00,
    imageUrl: 'https://picsum.photos/400/500?random=320',
    images: ['https://picsum.photos/800/1000?random=320'],
    description: 'Add a dash of personality to your tailoring with this silk pocket square, featuring a vibrant, intricate pattern and hand-rolled edges.',
    reviews: [],
  },
  {
    id: 33,
    name: 'Flannel Plaid Shirt',
    category: 'Shirts',
    price: 105.00,
    imageUrl: 'https://picsum.photos/400/500?random=330',
    images: ['https://picsum.photos/800/1000?random=330'],
    description: 'Crafted from incredibly soft cotton flannel, this shirt features a classic plaid pattern and is brushed for extra comfort. A perfect choice for cooler weather.',
    reviews: [],
    originalPrice: 130.00,
  },
  {
    id: 34,
    name: 'Chambray Workshirt',
    category: 'Shirts',
    price: 98.00,
    imageUrl: 'https://picsum.photos/400/500?random=340',
    images: ['https://picsum.photos/800/1000?random=340'],
    description: 'A rugged yet refined staple, this workshirt is made from lightweight chambray fabric and features two buttoned chest pockets. It gets softer with every wash.',
    reviews: [],
  },
];